### ISSUE TITLE
Wrong epoch date in README?

### ISSUE THREAD

**Issue by Sanva** [segmentio/ksuid#40]
Maybe I'm misunderstanding something, but, isn't the date in README wrong?

I mean, where it says

> The timestamp epoch is adjusted to **March 5th, 2014** [...]

, shouldn't it be *May 13th, 2014* ? Given that

```
go run ./ksuid -f inspect 000000000000000000000000000
```

outputs

```
REPRESENTATION:

  String: 000000000000000000000000000
     Raw: 0000000000000000000000000000000000000000

COMPONENTS:

       Time: 2014-05-13 18:53:20 +0200 CEST
  Timestamp: 0
    Payload: 00000000000000000000000000000000

```
